server:
  port: 3001
  servlet:
    context-path: /api/consumer
spring:
  application:
    name: spring-cloud-user-consumer
eureka:
  client:
    # 是否向注册中心注册自己，缺省：true
    register-with-eureka: true
    # 是否从Eureka获取注册信息，缺省：true
    fetch-registry: true
    # Eureka服务器的地址，类型为HashMap，缺省的Key为 defaultZone；缺省的Value为 http://localhost:8761/eureka
    # 如果服务注册中心为高可用集群时，多个注册中心地址以逗号分隔。
    service-url:
#      defaultZone: http://eureka1001:1001/eureka/,http://eureka1002:1002/eureka/,http://eureka1003:1003/eureka/
      defaultZone: http://eureka1001:1001/eureka/
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
    instance-id: ${spring.application.name}:${server.port}
    lease-renewal-interval-in-seconds: 10

feign:
  circuitbreaker:
    enabled: true
#熔断器超时不能卸载feign：下面，另起
hystrix:
  dashboard:
    proxy-stream-allow-list: 127.0.0.1
  command:
    default:
      execution:
        timeout:
          #如果enabled设置为false，则请求超时交给ribbon控制,为true,则超时作为熔断根据
          enabled: true
        isolation:
          # FeignConfiguration中的attributes获取不到
          strategy: SEMAPHORE
          thread:
            timeoutInMilliseconds: 2000

# ribbon超时时间配置 （如果不配置的话默认是1000毫秒超时）
#ribbon:
#  ReadTimeout: 10000
#  ConnectTimeout: 10000

client:
  application:
    name:
      department: ${DEPARTMENT_APPLICATION_NAME:spring-cloud-department-provider}
