server:
  port: 4001
  servlet:
    context-path: /api/provider
spring:
  application:
    name: spring-cloud-department-provider
eureka:
  client:
    # 是否向注册中心注册自己，缺省：true
    register-with-eureka: true
    # 是否从Eureka获取注册信息，缺省：true
    fetch-registry: true
    # Eureka服务器的地址，类型为HashMap，缺省的Key为 defaultZone；缺省的Value为 http://localhost:8761/eureka
    # 如果服务注册中心为高可用集群时，多个注册中心地址以逗号分隔。
    service-url:
#      defaultZone: http://eureka1001:1001/eureka/,http://eureka1002:1002/eureka/,http://eureka1003:1003/eureka/
      defaultZone: http://eureka1001:1001/eureka/
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
    instance-id: ${spring.application.name}:${server.port}
